name: elapsed
description: Get time elapsed for asynchronous function in a single line of code.
version: 1.2.0
homepage: https://github.com/xamantra/elapsed

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.5
  http: ^0.13.0